<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="EVACUAZIONE_SCARTI" Id="{e1e90f84-2da5-421e-ac38-8582f800e994}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM EVACUAZIONE_SCARTI
VAR

	bINIT					:BOOL;
	
	//act Area MACINATORE
	rtAuto_ON				:R_TRIG;
	ftAuto_ON				:F_TRIG;
	tmrT3_ON				:TON;	
	tmrT3_OFF				:TON;		
	tmrT1T2_ON				:TON;	
	tmrT1T2_OFF				:TON;
	ft_AbilitaT1T2			:F_TRIG;
	ft_AbilitaT3			:F_TRIG;
	ft_AbilitaT4			:F_TRIG;
	
	Area_HS_On				:BOOL;
	rt_Area_M_Riarmo		:R_TRIG;
	rt_Area_M_Disarmo		:R_TRIG;
	tmr_SvuotaT1			:TON;		
	tmr_SvuotaT2			:TON;	
	tmr_SvuotaT3			:TON;	
	tmr_MacinatoreON		:TON;
	tmr_MacinatoreOFF		:TON;
	rt_MacinatoreON			:R_TRIG;
	rt_MacinatoreOFF		:R_TRIG;
	rt_MPO1_btn_M_MacOn		:R_TRIG;
	rt_btn_Fsx_T3StartMan	:R_TRIG;
	rt_btn_Fdx_T4StartMan	:R_TRIG;
	tmr_T3T5T6DelayStart	:TON;
	rt_T3S1full				:R_TRIG;
	tmr_T3S1vuoto			:TON;
	tmr_T3S1pieno			:TON;
	bT3S1full				:BOOL;
	rt_T3S2full				:R_TRIG;
	tmr_T3S2vuoto			:TON;
	bT3S2full				:BOOL;
	ft_T3S2full				:F_TRIG;
	countT3avanzamento		:INT;
	
	//act AREA SILOS
	rt_Area_S_Riarmo		:R_TRIG;
	rt_Area_S_Disarmo		:R_TRIG;
	
	//act_ALARM
	rtAlarmReset			:R_TRIG;	
	AlarmActive				:BOOL;
	AlarmReset				:BOOL;
	AlarmMask				:DWORD;
	T5_Bloccato				:ES_ALARM;	
	T6_Bloccato				:ES_ALARM;
	tmr_T4ON				:TON;
	
	tmrT3_Lavoro			:TON;	
	tmrT3_Pausa				:TON;
	tmrT5T6_RitStop			:TOF;	
	tmrS1_T_Rit_Empty		:TOF;
	tmrT1S01_Full			:TON;
	tmr_T_Rit_Stop_T4T5T6	:TOF;
	
	Forza_TT1S01_Full		:BOOL;
	
	appT1S01_Full			: BOOL;
	
	En_T_RitStopT5T6		:BOOL;
	
	//SENSORI	
	S1						:ES_S1;
	S2						:ES_S2;
	T1						:ES_T1;
	T3						:ES_T3;
	T5						:ES_T5;
	T6						:ES_T6;
                        	
	T1SO1tmravg				:TON;
	T1SO1arravg				:ARRAY[0..99]OF INT;
	T1SO1maxCnt				:INT;
	T1SO1sumavg				:REAL;
	T1SO1avg				:REAL;
	T1SO1cnt				:INT;
	T1SO1cnt2				:INT;	
	T1SO1cnt3				:INT;
	                    	
	S1SO2tmravg				:TON;
	S1SO2arravg				:ARRAY[0..99]OF INT;
	S1SO2maxCnt				:INT;
	S1SO2sumavg				:REAL;
	S1SO2avg				:REAL;
	S1SO2cnt				:INT;
	S1SO2cnt2				:INT;	
	S1SO2cnt3				:INT;		
                        	
	T3S1tmravg				:TON;
	T3S1arravg				:ARRAY[0..99]OF INT;
	T3S1maxCnt				:INT;
	T3S1sumavg				:REAL;
	T3S1avg					:REAL;
	T3S1cnt					:INT;
	T3S1cnt2				:INT;	
	T3S1cnt3				:INT;
	                    	
	T3S2tmravg				:TON;
	T3S2arravg				:ARRAY[0..99]OF INT;
	T3S2maxCnt				:INT;
	T3S2sumavg				:REAL;
	T3S2avg					:REAL;
	T3S2cnt					:INT;
	T3S2cnt2				:INT;	
	T3S2cnt3				:INT;
	                    	
	//SEMAFORI          	
	fbS1_Se1				:FB_Semaforo;
		
	//gestione filtro temporale sensore 
	SO2_full_curr			:BOOL;
	tmrValidaSoglia_S02		:TON;

	
	//gestione macinatore
	TON_Macinatore_On			:TON;
	TON_Vibro_Macinatore_On		:TON;
	TON_Ciclo_Macinatore		:TON;
	TP_Start_Macinatore			:TP;
	TP_Stop_Macinatore			:TP;

	TS							:BOOL;
	M_Ciclo_Svuotamento_Hdd_RUN	:BOOL;
	M_Auto_Start_Macinatore		:BOOL;
	M_Auto_Start_Vibro_Macinatore		:BOOL;
	M_Auto_Start_Vibro_Hdd		:BOOL;
	M_Start_Req_Stop_Macinatore	:BOOL;	
	M_Stop_Req_Stop_Macinatore	:BOOL;
	
	M_Man_Start_Vibro_Hdd		:BOOL;
	
	
	
	
	//TwinsAFE
	tmrErrAck				:TON;	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
act_INIT();

act_ALARM();

act_INPUT();

act_Sensori();

act_AreaSilos();

act_Macinatore();

//act_AreaMac_AUTO();
//act_AreaMac_MAN();

act_Semafori();

act_OUTPUT();

act_HMI();]]></ST>
    </Implementation>
    <Action Name="act_ALARM" Id="{5ded8dbe-8890-4ab2-a626-b7c56d7ddc25}">
      <Implementation>
        <ST><![CDATA[
//TwinSAFE
TS_ErrAck := C1P1_Rst_Eme OR R1P1_Rst_Eme;


tmrErrAck(IN:=TS_ErrAck,PT:=T#1S);
IF tmrErrAck.Q THEN
	TS_ErrAck:=FALSE;
END_IF




//ALLARMI DA SENSORI
rtAlarmReset(CLK:=bAlarmReset);
IF rtAlarmReset.Q THEN
	bAlarmReset:=FALSE;
	T5.Alarm.Active:=FALSE;	
	T6.Alarm.Active:=FALSE;	
	bAllarmeT5:=FALSE;
	bAllarmeT6:=FALSE;
END_IF

IF NOT AlarmActive THEN

	//Allarme T5 Bloccato - 5s
	IF HQ1_T5_KA5 THEN
		T5.Alarm.tmr(IN:=TRUE,PT:=INT_TO_TIME(T5.Alarm.pt*1000));
		IF T5.Alarm.tmr.ET < T5.Alarm.tmr.PT THEN
			T5.S1_rt(CLK:=T5_S1);
			IF T5.S1_rt.Q THEN
				T5.S1_letto:=TRUE;		
			END_IF
		END_IF
	
		IF T5.Alarm.tmr.Q THEN
			IF NOT T5.S1_letto AND HQ1_T5_KA5 THEN
				T5.Alarm.Active:=TRUE AND bAllarmeT5enable;	
			ELSE	
				T5.Alarm.Active:=FALSE;	
			END_IF
			T5.S1_letto:=FALSE;
			T5.Alarm.tmr(IN:=FALSE);
		END_IF
	END_IF

	
	
		
	//Allarme T6 Bloccato - 5s
	IF HQ1_T6_KA6 THEN
		T6.Alarm.tmr(IN:=TRUE,PT:=INT_TO_TIME(T6.Alarm.pt*1000));
		IF T6.Alarm.tmr.ET < T6.Alarm.tmr.PT THEN
			T6.S1_rt(CLK:=T6_S1);
			IF T6.S1_rt.Q THEN
				T6.S1_letto:=TRUE;		
			END_IF
		END_IF
	
		IF T6.Alarm.tmr.Q THEN
			IF NOT T6.S1_letto AND HQ1_T6_KA6 THEN
				T6.Alarm.Active:=TRUE AND bAllarmeT6enable;	
			ELSE	
				T6.Alarm.Active:=FALSE;	
			END_IF
			T6.S1_letto:=FALSE;
			T6.Alarm.tmr(IN:=FALSE);
		END_IF	
	END_IF
	

	
	
	//Allarme S2 Silos Pieno
	IF S2.S1_full (*AND glo_ES_BtnHMI.S2_Alarm_Enable*) THEN
		S2.Alarm.Active := TRUE AND bAllarmeS2S1enable;
	END_IF
	
	
	
	
	//Allarme T3 Bloccato - 30s
	IF T1.SO1_full AND T3.S1_full THEN
		T3.Alarm.tmr(IN:=TRUE,PT:=INT_TO_TIME(T3.Alarm.pt*1000));
		IF T3.Alarm.tmr.Q THEN
			T3.Alarm.tmr(IN:=FALSE);
			T3.Alarm.Active := TRUE;	
		END_IF
	ELSE
		T3.Alarm.Active := FALSE;
	END_IF	

	
	
	
	//Allarme S1 Silos1 Pieno
	IF (*S1_S2_full AND*) S1_S2 THEN
		S1.Alarm.Active:=TRUE;
	END_IF
	
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_AreaMac_AUTO" Id="{4299c151-616b-42a7-806f-5a6703d8c57a}">
      <Implementation>
        <ST><![CDATA[
//#######################################################
//###################    AREA M ON    ###################
//#######################################################

IF M_PO1.key THEN
	rt_Area_M_Riarmo(CLK:= M_PO1.btn_R_Riarmo OR bSIMULA_btnR);
	IF rt_Area_M_Riarmo.Q THEN
		bSIMULA_btnR:=FALSE;
		AreaM_ON:= TRUE;
	END_IF
END_IF
rt_Area_M_Disarmo(CLK:= M_PO1.btn_0_AreaMoff OR bSIMULA_btn0);
IF NOT M_PO1.key OR rt_Area_M_Disarmo.Q OR NOT TS_AreaM_ON OR NOT TS_AreaS_ON (*OR NOT TS_AreaM_OFF*) THEN
	bSIMULA_btn0:=FALSE;	
	AreaM_ON:=FALSE;
	fun_AreaM_SPEGNITUTTO();	
END_IF

//#######################################################
//##################     AUTOMATICO   ###################
//#######################################################

rtAuto_ON(CLK:=HQ1_Auto_ON OR bSIMULAAuto_ON);
IF rtAuto_ON.Q THEN
	bIsAuto:=TRUE;
END_IF
ftAuto_ON(CLK:=HQ1_Auto_ON OR bSIMULAAuto_ON);
IF ftAuto_ON.Q THEN
	bIsAuto:=FALSE;	
	bSIMULA_btn0:=TRUE;	
	bSIMULA_btn0silos:=TRUE;	
	fun_AreaM_SPEGNITUTTO();	
END_IF

IF bIsAuto THEN
	

	//#######################################################
	//####################     T1 - T2    ###################
	//#######################################################
	
	(*
	- sensore sotto hundegger dà che T1 è pieno
	- area attiva
	- sensore all'inizio del T3 dà che è vuoto/libero
	- T3 non è bloccato: sensori del T1 e T3 contemporaneamente non pieni
	*)
	
	IF bAbilitaT1T2 THEN
		
		CASE stepT1T2 OF
			
			0:
				descT1T2:='T1-T2 spenti. In attesa di T1SO1 pieno';
				IF T1.SO1_full THEN
					stepT1T2:=5;
				END_IF
			
			5:
				IF NOT T3.S1_full (*AND NOT T3.Alarm.Active*) THEN 
					descT1T2:='Avvio T1-T2';
					bT1_ON:=TRUE;
					bT2_ON:=TRUE;
					tmrT1T2_ON(IN:=FALSE);
					stepT1T2:=10;
				ELSIF T3.S1_full (*OR T3.Alarm.Active*) THEN
					stepT1T2:=100;
				END_IF
			
			10:
				descT1T2:='T1-T2 accesi per 2s';
				tmrT1T2_ON(IN:=TRUE,PT:=T#2S);
				IF tmrT1T2_ON.Q THEN
					tmrT1T2_OFF(IN:=FALSE);
					stepT1T2:=15;					
				END_IF
			
			15:
				descT1T2:='T1-T2 accesi finchè T3S1 pieno';		
				IF NOT T1.SO1_full THEN
					tmrT1T2_ON(IN:=FALSE);					
					bT1_ON:=FALSE;
					stepT1T2:=16;
				END_IF		
				tmr_T3S1pieno(in:=T3.S1_full,PT:=T#2S);
				IF tmr_T3S1pieno.Q THEN
					bT1_ON:=FALSE;
					bT2_ON:=FALSE;
					stepT1T2:=20;				
				END_IF
	
			16:
				descT1T2:='T1spento, T2 acceso per 15s o finchè T3S1 pieno';	
				tmrT1T2_ON(IN:=TRUE,PT:=T#15S);	
				IF tmrT1T2_ON.Q OR T3.S1_full THEN
					bT2_ON:=FALSE;
					stepT1T2:=20;
				END_IF	
		
			20:
				descT1T2:='T1-T2 spenti, pausa 30s';
				tmrT1T2_OFF(IN:=TRUE,PT:=T#30S);
				IF tmrT1T2_OFF.Q THEN
					stepT1T2:=100;						
				END_IF
			
			100:
				tmrT1T2_OFF(IN:=FALSE);
				tmrT1T2_ON(IN:=FALSE);
				bT1_ON:=FALSE;
				bT2_ON:=FALSE;
				stepT1T2:=0;
					
		END_CASE
			
	END_IF
	ft_AbilitaT1T2(CLK:=bAbilitaT1T2);
	IF ft_AbilitaT1T2.Q THEN
		descT1T2:='T1-T2 disabilitati';
		HQ1_T1_KA1:=FALSE;
		HQ1_T2_KA2:=FALSE;
		bT1_ON:=FALSE;
		bT2_ON:=FALSE;
		stepT1T2:=100;			
	END_IF
	
	
	
	//#######################################################
	//##############    M - T3 - T5 - T6    #################
	//#######################################################
	
	(*
	- area attiva
	- bottone Macinatore da pulsantiera (vedi sotto fuori dall'automatico)
	- sensore all'inizio del T3 dà che è pieno
	- Silos2 non deve essere pieno
	- T5 non bloccato controllo paletta
	- T6 non bloccato controllo paletta
	*)
	IF NOT bAbilitaT3 THEN
		
		countT3avanzamento:=0;
		
	END_IF
	
	IF bAbilitaT3 THEN
	
		//azzeramento step automatici se il macinatore è stato avviato in locale
	//	IF NOT M_Start_Macinatore_Loc THEN
		//	stepT3 :=0;
	//	END_IF;
		CASE stepT3 OF
			
			0:
				descT3:='T3 fermo. In attesa di T3S1 pieno';
				IF NOT bT4_ON THEN// AND NOT M_Start_Macinatore_Loc THEN
					tmrT3_OFF(IN:=FALSE);
					tmrT3_ON(IN:=FALSE);
					IF T3.S1_full THEN	
						//PIENO INGRESSO, USCITA SCARICA -> ACCENDO T3						
						tT3ON_auto:=15;
						IF countT3avanzamento >=5 THEN
							descT3:='Macinatore acceso, attendo 20s per avvio T3';
							bM_ON:=TRUE;
							stepT3:=10;	
						ELSE
							descT3:='T3 acceso per 30s';
							bT3_ON:=TRUE;
							stepT3:=5;	
						END_IF	
					END_IF
				END_IF
		
			5:
				descT3:='T3 acceso per 30s';
				bT3_ON:=TRUE;
				tmrT3_ON(IN:=TRUE,PT:=INT_TO_TIME(tT3ON_auto*1000));
				IF tmrT3_ON.Q OR T3.S2_full THEN
					bT3_ON:=FALSE;	
					tmrT3_OFF(IN:=FALSE);
					countT3avanzamento:=countT3avanzamento+1;
					stepT3:=20;
				END_IF	
			
			10:
				descT3:='Macinatore acceso, attendo 20s per avvio T3';
				tmrT3_OFF(IN:=TRUE,PT:=T#20S);
				IF tmrT3_OFF.Q THEN
					bT3_ON:=TRUE;
					T3_ModoPausaLavoro:=TRUE;
					bT3EnT1PausaLavoro:=TRUE;  (*abilito un timer per far lavorare T3 pausa-lavoro per non intasare T5*)
					bT3EnT2PausaLavoro:=FALSE;
					T3_Lavoro:=TRUE;
					stepT3:=15;
				END_IF
		
			15:
				descT3:='T3 e Macinatore accesi per 5min';
				tmrT3_ON(IN:=TRUE,PT:=T#8M);
				IF tmrT3_ON.Q THEN
					tmrT3_OFF(IN:=FALSE);
					bM_ON:=FALSE;
					bT3_ON:=FALSE;
					T3_ModoPausaLavoro:=FALSE;
					bT3EnT1PausaLavoro:=FALSE;
					bT3EnT2PausaLavoro:=FALSE;
					T3_Lavoro:=FALSE;
					stepT3:=20;
					countT3avanzamento:=0;
				END_IF
				
			20:
				descT3:='Tutto spento, pausa di 30s';
				tmrT3_OFF(IN:=TRUE,PT:=T#30S);
				IF tmrT3_OFF.Q THEN
					tmrT3_OFF(IN:=FALSE);
					stepT3:=0;
				END_IF
			
			100:
				tmrT3_OFF(IN:=FALSE);
				tmrT3_ON(IN:=FALSE);
				bM_ON:=FALSE;
				stepT3:=0;
		
		END_CASE
	
	END_IF
	ft_AbilitaT3(CLK:=bAbilitaT3);
	IF ft_AbilitaT3.Q THEN
		descT3:='T3 disabilitato';
		HQ1_T3_KA3:=FALSE;	
		bMacinatoreStart:=FALSE;
		bMacinatoreStop:=TRUE;
		stepT3:=100;		
	END_IF
	
	
	
	//#######################################################
	//#################     T4 - T5 - T6    #################
	//#######################################################
	
	(*
	- T5 non bloccato controllo paletta
	- T6 non bloccato controllo paletta
	- Silos2 non deve essere pieno
	- Consenso da logica Aspirazione
	*)
	
	IF bAbilitaT4 THEN
		
		CASE stepT4 OF
			
		0:
			descT4:='T4 fermo. In attesa di LogicaAspirazioneON';
			IF (NOT bT3_ON AND bMacinatoreStop) AND LogicaAspirazioneON THEN
				bT4_ON:=TRUE;
				stepT4:=10;
			END_IF
		
		10:
			descT4:='T4 acceso per 30s';
			tmr_T4ON(IN:=TRUE,PT:=T#30S);	
			IF tmr_T4ON.Q THEN
				tmr_T4ON(IN:=FALSE);
				IF NOT LogicaAspirazioneON THEN
					stepT4:=100;			
				END_IF				
			END_IF
			
		100:
			tmr_T4ON(IN:=FALSE);
			bT4_ON:=FALSE;
			stepT4:=0;
					
		END_CASE

	END_IF
	ft_AbilitaT4(CLK:=bAbilitaT4);
	IF ft_AbilitaT4.Q THEN
		descT4:='T4 disabilitato';
		HQ1_T4_KA4:=FALSE;
		bT4_ON:=FALSE;
		stepT4:=100;			
	END_IF
	
END_IF



//####################################################################
//####     GESTIONE TIMER PAUSA LAVORO IN CICLO AUTOMATICO T3 #######
//###################################################################

tmrT3_Lavoro(IN:=bT3EnT1PausaLavoro,PT:=T#20S);
tmrT3_Pausa(IN:=bT3EnT2PausaLavoro,PT:=T#30S);

IF tmrT3_Lavoro.Q THEN
	bT3EnT1PausaLavoro := FALSE;	
	bT3EnT2PausaLavoro := TRUE;
	T3_Lavoro := FALSE;	
END_IF

IF tmrT3_Pausa.Q THEN
	bT3EnT1PausaLavoro := TRUE;	
	bT3EnT2PausaLavoro := FALSE;
	T3_Lavoro := TRUE;
END_IF

//##################################################################
//####     		 GESTIONE TIMER RITARDO STOP T5-T6	 		 #######
//##################################################################
En_T_RitStopT5T6 := bM_ON AND AreaM_ON;
tmrT5T6_RitStop(IN:=En_T_RitStopT5T6,PT:=T#30S);

//#######################################################
//####     USCITE INDIPENDENDI DA MODO AUTO/MAN   #######
//#######################################################

HQ1_T1_KA1:= bT1_ON AND AreaM_ON;
HQ1_T2_KA2:= bT2_ON AND AreaM_ON;

M_Cmd_T3 := bT3_ON AND (T3_Lavoro OR NOT T3_ModoPausaLavoro);

HQ1_T3_KA3:= M_Cmd_T3 AND NOT SensInMac AND AreaM_ON AND NOT (T5.Alarm.Active OR T6.Alarm.Active OR S2.Alarm.Active);		
HQ1_T4_KA4:= bT4_ON AND AreaM_ON AND LogicaAspirazioneON AND NOT (T5.Alarm.Active OR T6.Alarm.Active OR S2.Alarm.Active);
HQ1_T5_KA5:= (bM_ON OR bT4_ON OR tmrT5T6_RitStop.Q) AND AreaM_ON AND NOT (T5.Alarm.Active OR T6.Alarm.Active OR S2.Alarm.Active);
HQ1_T6_KA6:= (bM_ON OR bT4_ON OR tmrT5T6_RitStop.Q) AND AreaM_ON AND NOT T6.Alarm.Active AND NOT S2.Alarm.Active;
		

bMacinatoreStart:= bM_ON AND AreaM_ON AND NOT (T5.Alarm.Active AND T6.Alarm.Active AND S2.Alarm.Active) and HQ1_T5_KA5;
bMacinatoreStop:= NOT bM_ON OR T5.Alarm.Active OR T6.Alarm.Active OR NOT HQ1_T5_KA5 OR NOT HQ1_T5_KA5;	

//#######################################################
//#############     START-STOP MACINATORE   #############
//#######################################################

//AVVIO MACINATORE RICHIEDE CHE DOPO 1s USCITA VENGA ABBASSATA
rt_MacinatoreON(CLK:=bMacinatoreStart);	
IF rt_MacinatoreON.Q THEN
	HQ1_M_ON:=TRUE;
	HQ1_M_OFF:=FALSE;

END_IF
tmr_MacinatoreON(IN:=HQ1_M_ON,PT:=T#1S);	
IF tmr_MacinatoreON.Q THEN
	tmr_MacinatoreON(IN:=FALSE);
	HQ1_M_ON:=FALSE;
END_IF
//SPEGNIMENTO MACINATORE RICHIEDE CHE DOPO 1s USCITA VENGA ABBASSATA
rt_MacinatoreOFF(CLK:=bMacinatoreStop);	
IF rt_MacinatoreOFF.Q THEN
	HQ1_M_ON:=FALSE;
	HQ1_M_OFF:=TRUE;

END_IF
tmr_MacinatoreOFF(IN:=HQ1_M_OFF,PT:=T#1S);	
IF tmr_MacinatoreOFF.Q THEN
	tmr_MacinatoreOFF(IN:=FALSE);
	HQ1_M_OFF:=FALSE;
END_IF
	
		
	
	

//#######################################################
//##################     PULSANTIERA   ##################
//#######################################################

IF AreaM_ON AND bAbilitaPulsatiera THEN
	
	//M	
	rt_MPO1_btn_M_MacOn(CLK:=(M_PO1.btn_M_MacOn OR bSIMULA_btnM));
	IF rt_MPO1_btn_M_MacOn.Q AND bMacinatoreStop THEN
		bSIMULA_btnM:=FALSE;
		//M SPENTO -> LO ACCENDO
		bM_ON:=TRUE;
		IF NOT SensInMac AND NOT HQ1_T4_KA4 THEN
			bT3T5T6DelayStart:= TRUE;
		END_IF		
	ELSIF rt_MPO1_btn_M_MacOn.Q AND bMacinatoreStart THEN
		//M ACCESO -> LO SPENGO
		bSIMULA_btnM:=FALSE;
		bM_ON:=FALSE;	
		bT3T5T6DelayStart:=FALSE;
		IF (*NOT M_PO1.btn_Fsx_T3StartMan AND*) NOT glo_ES_ActVal.PuliziaT1t2_ON THEN
			bT3_ON:=FALSE;
			M_Start_Macinatore_Loc := FALSE;
		END_IF
	END_IF
	
	IF (T5.Alarm.Active OR T6.Alarm.Active OR S2.Alarm.Active) THEN
		bM_ON:=FALSE;
	END_IF
		
	//AVVIO RITARDATO DEL T3,T5,T6 DOPO 15s DALL'AVVIO M	
	tmr_T3T5T6DelayStart(IN:=bT3T5T6DelayStart, PT:=T#35S);
	IF tmr_T3T5T6DelayStart.Q THEN
		bT3T5T6DelayStart:=FALSE;
		bT3_ON:=TRUE;
		M_Start_Macinatore_Loc := TRUE;
	END_IF
	
	//T3
	rt_btn_Fsx_T3StartMan(CLK:=M_PO1.btn_Fsx_T3StartMan OR bSIMULA_btnT3);		//FRECCIA A SINISTRA SU BOTTONE DI SINISTRA
	IF rt_btn_Fsx_T3StartMan.Q THEN
		IF NOT SensInMac AND NOT HQ1_T3_KA3 THEN				//SE SENSORE SU MAC è ON, ALLORA NN ACCENDO T3 XKE LO INTASO
			bSIMULA_btnT3:=FALSE;
			bT3_ON:= TRUE;
		ELSIF NOT glo_ES_ActVal.PuliziaT1t2_ON AND HQ1_T3_KA3 THEN
			bSIMULA_btnT3:=FALSE;
			bT3_ON:=FALSE;
		END_IF			
	END_IF
	
	IF NOT bM_ON THEN 
		bT3_ON:=FALSE;
	END_IF
	
	//T4
	rt_btn_Fdx_T4StartMan(CLK:=M_PO1.btn_Fsx_T4StartMan);
	IF rt_btn_Fdx_T4StartMan.Q THEN		//FRECCIA A SINISTRA SU BOTTONE DI DESTRA
		IF NOT HQ1_T4_KA4 THEN	
			bT4_ON:= TRUE;
		ELSE
			bT4_ON:=FALSE;
		END_IF
	END_IF
		
	//T7
	IF M_PO1.btn_Fup_T7Avanti THEN			//FRECCIA IN SU
		HQ1_T7_A_KA8:= TRUE;
		HQ1_T7_I_KA9:= FALSE;
	ELSIF M_PO1.btn_Fdw_T7Indietro THEN		//FRECCIA IN GIU'
		HQ1_T7_I_KA9:= TRUE;
		HQ1_T7_A_KA8:=FALSE;
	ELSE
		HQ1_T7_A_KA8:=FALSE;
		HQ1_T7_I_KA9:= FALSE;
	END_IF
	
END_IF



]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_AreaMac_MAN" Id="{bef5b37c-250d-481b-88f3-c81af9c4d0fa}">
      <Implementation>
        <ST><![CDATA[
//#######################################################
//####################     MANUALE   ####################
//#######################################################


IF NOT bIsAuto THEN
		
	//#######################################################
	//###############     PULIZIA T1-T2-T3   ################
	//#######################################################

	IF 	bMAN_SvuotaT1T2T3 THEN
		bMAN_SvuotaT1T2T3:=FALSE;
		glo_ES_ActVal.PuliziaT1T2_ON:=TRUE;
		bT1_ON:= TRUE;
		bT2_ON:= TRUE;
		bM_ON:= TRUE;
		bT3T5T6DelayStart:=TRUE;
	END_IF
	IF glo_ES_ActVal.PuliziaT1T2_ON THEN
		tmr_SvuotaT1(IN:= bT1_ON,PT:=DINT_TO_TIME(glo_ES_Config.T1_Time*1000));
		tmr_SvuotaT2(IN:= bT2_ON,PT:=DINT_TO_TIME(glo_ES_Config.T2_Time*1000));
		tmr_SvuotaT3(IN:= bM_ON,PT:=DINT_TO_TIME(glo_ES_Config.T3_Time*1000));
	END_IF

	//STOP T1
	IF tmr_SvuotaT1.Q THEN
		tmr_SvuotaT1(IN:=FALSE);
		bT1_ON:= FALSE;
	END_IF
		
	//STOP T2
	IF tmr_SvuotaT2.Q THEN
		tmr_SvuotaT2(IN:=FALSE);
		bT2_ON:= FALSE;
	END_IF
	
	//STOP T3	
	IF tmr_SvuotaT3.Q THEN
		tmr_SvuotaT3(IN:=FALSE);
		bM_ON:= FALSE;
		bT3T5T6DelayStart:=FALSE;
		glo_ES_ActVal.PuliziaT1t2_ON:=FALSE;
	END_IF

	
	//#######################################################
	//#################     PULIZIA S1-T4   #################
	//#######################################################
	
	IF bMAN_SvuotaS1T4 THEN
		bMAN_SvuotaS1T4:=FALSE;
		
	END_IF
	
	
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_AreaSilos" Id="{fbbd07a1-ba70-47aa-afaa-1b6eeda18dc2}">
      <Implementation>
        <ST><![CDATA[
//#######################################################
//###################    AREA S ON    ###################
//#######################################################

IF S1_PO1.key THEN
	rt_Area_S_Riarmo(CLK:= S1_PO1.btn_R_Riarmo OR bSIMULA_btnRsilos);
	IF rt_Area_S_Riarmo.Q THEN
		bSIMULA_btnRsilos:=FALSE;
		AreaS_ON:= TRUE;
	END_IF
END_IF
rt_Area_S_Disarmo(CLK:= S1_PO1.btn_0_AreaMoff OR bSIMULA_btn0silos);
IF NOT S1_PO1.key OR rt_Area_S_Disarmo.Q OR NOT TS_AreaM_ON OR NOT TS_AreaS_ON (*OR TS_AreaS_OFF*) THEN
	bSIMULA_btn0silos:=FALSE;	
	AreaS_ON:=FALSE;
END_IF

	//led pulsante area macinatore ON
	S1_PO1.led_0_AreaMoff := AreaS_ON;

	//led pulsante riarmo area macinatore
	S1_PO1.led_R_Riarmo := TS_AreaS_ON;
	
	//riarmo emergenze
//	TS_S1PO1_btn_R := S1_PO1.key AND S1_PO1.btn_R_Riarmo;
	TS_S1PO1_btn_R := S1_PO1.key AND(C1P1_Rst_Eme OR R1P1_Rst_Eme);
	
	
//#######################################################
//#############    LOGICA M-ASPIRAZIONE   ###############
//#######################################################

IF AreaS_ON AND bAbilitaPulsatieraS1PO1 THEN
	
	//VALVOLA STELLARE S1_SO2	
	IF (S1.SO2_full) AND NOT bT3_ON AND bMacinatoreStop AND NOT bSIMULA_BrichettatriceON AND bAbilitaT4 THEN
		HQ1_S1_ValvolaStellare:=TRUE;
	ELSE
		HQ1_S1_ValvolaStellare:=FALSE;
	END_IF
	
//	HQ1_S1_ValvolaStellare:=FALSE;
	
	//BRICCHETTATRICE
	IF (*HQ1_ScorniciatriceON AND NOT HQ1_S1_ValvolaStellare AND*) bSIMULA_BrichettatriceON THEN
		HQ1_BrichettatriceON:=TRUE;
	ELSE
		HQ1_BrichettatriceON:=FALSE;
	END_IF
	
	//RACLA
	IF HQ1_BrichettatriceON OR HQ1_S1_ValvolaStellare THEN
		HQ1_RaclaON:=TRUE;
	ELSE
		HQ1_RaclaON:=FALSE;
	END_IF 
	
	//CONSENSO A T4 T5 T6
tmr_T_Rit_Stop_T4T5T6(IN:=HQ1_S1_ValvolaStellare,PT:=T#1M);
	
IF tmr_T_Rit_Stop_T4T5T6.Q THEN
		LogicaAspirazioneON:=TRUE;
	ELSE
		LogicaAspirazioneON:=FALSE;		
	END_IF
	
END_IF


]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_HMI" Id="{96798d00-c201-4db6-89ef-c78d6fd7f48c}">
      <Implementation>
        <ST><![CDATA[

bAllarmeT3	:= T3.Alarm.Active;			
bAllarmeT5	:= T5.Alarm.Active;			
bAllarmeT6	:= T6.Alarm.Active;
bAllarmeS2S1:= S2.Alarm.Active;

bT1SO1pieno	:= T1.SO1_full;
bT3S1pieno	:= T3.S1_full;
bT3S2pieno	:= T3.S2_full;
bS1SO2pieno	:= S1.SO2_full;
bS2S1pieno	:= S2.S1_full;

glo_ES_ActVal.T3_S1:= T3.S1_actVal;
glo_ES_ActVal.T3_S2:= T3.S2_actVal;
glo_ES_ActVal.S2_S1:= S2.S1_actVal;
glo_ES_ActVal_T1_SO1:= T1_SO1;

altMatT3S1:=T3.S1_fb.distanzaAVuoto - T3.S1_actVal;
IF altMatT3S1 <0 THEN
	altMatT3S1:=0;
END_IF
altMatT3S2:=T3.S2_fb.distanzaAVuoto - T3.S2_actVal;
IF altMatT3S2 <0 THEN
	altMatT3S2:=0;
END_IF 
distMatT1SO1:= T1.SO1_fb.distanzaAVuoto - T1.SO1_actVal;
IF distMatT1SO1 <0 THEN
	distMatT1SO1:=0;
END_IF 

IF sogliaT3S1 = 0 THEN
	sogliaT3S1:=100;
END_IF
IF sogliaT3S2 = 0 THEN
	sogliaT3S2:=40;
END_IF
//IF sogliaS1SO2 = 0 THEN
//	sogliaS1SO2:=1000;
//END_IF
IF solgiaT1SO1 = 0 THEN
	solgiaT1SO1:=5000;
END_IF 

]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_INIT" Id="{580611ca-94a3-4bcb-8752-e13d8ff1ce45}">
      <Implementation>
        <ST><![CDATA[
IF NOT bINIT THEN
	
	bINIT:=TRUE;

	bMacinatoreStop:=TRUE;

	//Avvia TwinSAFE Gruppo EVACUAZIONE SCARTI
	TS_Run_GrpES:=TRUE;

END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_INPUT" Id="{9c994c28-22a6-4f62-a8c2-2a9862140083}">
      <Implementation>
        <ST><![CDATA[
//TERM7 EL1008 H-Q1
SensInMac				:= glo_dig_in_HQ1[1];		//DIGIN CH1			Sensore ingresso macinatore
R5_S2					:= glo_dig_in_HQ1[2];		//DIGIN CH2			Val1 aperta
T5_S3					:= glo_dig_in_HQ1[3];		//DIGIN CH3			Val2 chiusa
S1_S3					:= glo_dig_in_HQ1[4];		//DIGIN CH4			Allarme silos1 pieno
T6_S1					:= glo_dig_in_HQ1[5];		//DIGIN CH5			Rotaz catena IFS289
HQ1_Auto_ON				:= glo_dig_in_HQ1[6];		//DIGIN CH6			Modo auto-man
HQ1_P1					:= glo_dig_in_HQ1[7];		//DIGIN CH7			Reset Allarme
HQ1_K1					:= glo_dig_in_HQ1[8];		//DIGIN CH8			---

//TERM8 EL1008 H-Q1
//HQ1_AspirazioneON		:= glo_dig_in_HQ1[10];		//DIGIN CH2			Motore aspirazione in silos S1
I_Fdbk_Km_Area_Nastri_Macinatore:= glo_dig_in_HQ1[9];		//DIGIN CH2			feedback contattore area macinatore
I_Fdbk_Km_Area_Macinatore:= glo_dig_in_HQ1[10];		//DIGIN CH2			feedback contattore area macinatore
I_Macinatore_Run		:= glo_dig_in_HQ1[12];		//DIGIN CH1			Scorniciatrice accesa

S1_S2					:= glo_dig_in_HQ1[12];		//DIGIN CH4			Sensore troppopieno in alto in silos S1
S1_S1					:= glo_dig_in_HQ1[13];		//DIGIN CH5			Sensore livello in basso in silos S1
HQ1_BricchettatriceON	:= glo_dig_in_HQ1[13];		//DIGIN CH6			Bricchettatrice accesa



//TERM11 EL3012 H-Q1
T3_S1					:= glo_analog_in_HQ1[1];	//ANALOGIN CH1		Pres materiale In T3
T3_S2					:= glo_analog_in_HQ1[2];	//ANALOGIN CH2		Pres materiale Out T3

//TERM12 EL3012 H-Q1
S1_SO2					:= glo_analog_in_HQ1[3];	//ANALOGIN CH1		Liv silos2 UMT 30-6000


(*****************************************************************)	
(*****************************************************************)	
(*****************************************************************)

//BOX16 EP6228-0022 M-CS1
T1_SO1					:= glo_analog_in_MCS1[1];	//IOLINK CH1	Già in mm. Pres mat T1, da inizio vibro fino sopra nastro  O1D120


(*****************************************************************)	
(*****************************************************************)	
(*****************************************************************)

//BOX17 EP6228-0022 T3-C01
S2_S1					:= glo_analog_in_T3C01[1];	//IOLINK CH2		LIV AVVIO VALV STELLARE UGT514

//S1_PO1											//IOLINK CH3		PULSANTIERA BNI005N
S1_PO1.key				:= glo_dig_in_T3C01[1];		//CHIAVE
S1_PO1.btn_0_AreaMoff	:= glo_dig_in_T3C01[2];		//BOTTONE '0'
S1_PO1.btn_R_Riarmo		:= glo_dig_in_T3C01[3];		//BOTTONE 'r'
I_Pls_Start_Vibro_Hdd	:= glo_dig_in_T3C01[7];

//M_PO1												//IOLINK CH4		PULSANTIERA BNI005M
M_PO1.key				:= glo_dig_in_T3C01[1];		//CHIAVE
M_PO1.btn_0_AreaMoff	:= glo_dig_in_T3C01[2];	//BOTTONE '0'
M_PO1.btn_R_Riarmo		:= glo_dig_in_T3C01[3];	//BOTTONE 'r'
M_PO1.btn_M_MacOn		:= glo_dig_in_T3C01[4];	//TASTO 'M'
M_PO1.btn_Fdw_T7Indietro:= glo_dig_in_T3C01[13];	//FRECCIA IN GIU'
M_PO1.btn_Fup_T7Avanti	:= glo_dig_in_T3C01[14];	//FRECCIA IN SU
M_PO1.btn_Fsx_T3StartMan:= glo_dig_in_T3C01[15];	//FRECCIA SX BTN SX
M_PO1.btn_Fsx_T4StartMan:= glo_dig_in_T3C01[16];	//FRECCIA SX BTN DX

T5_S1					:= glo_dig_in_T3C01[25];	//DIGIN  CH7		ROTAZ CATENA IFS289
T5_SO1					:= glo_analog_in_T3C01[2];	//IOLINK CH8		LIV SCARICO MAC UGT525

//
I_Barriera_Macinatore := glo_dig_in_T3C01[10];









]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_Macinatore" Id="{587ecde4-fc76-4b85-b7a1-c25e2716cfdf}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Ld"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"ripristino barriere macinatore"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"TS_MPO1_Rst_Area_Macinatore"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">3L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">7L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"M_PO1.btn_R_Riarmo"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">10L</v>
                              </o>
                              <v n="Id">9L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"I_Fdbk_Km_Area_Macinatore"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">6L</v>
                              </o>
                              <v n="Id">5L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">8L</v>
                        </o>
                        <v n="Id">4L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"led pulsante area macinatore ON"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_PO1.led_0_AreaMoff"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">16L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TS_AreaM_ON"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">218L</v>
                          </o>
                          <v n="Id">217L</v>
                        </o>
                        <v n="Id">17L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">14L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"led pulsante riarmo area macinatore"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_PO1.led_R_Riarmo"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">23L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TS_AreaM_ON"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">22L</v>
                          </o>
                          <v n="Id">21L</v>
                        </o>
                        <v n="Id">24L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">20L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"led macinatore run"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_PO1.led_M_MacOn"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">181L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"I_Macinatore_Run"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">184L</v>
                          </o>
                          <v n="Id">183L</v>
                        </o>
                        <v n="Id">182L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">173L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"start ciclo macinatore da hundegger
"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_Ciclo_Svuotamento_Hdd_RUN"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">35L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">27L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">98L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" />
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">108L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"PB_Start_Svuotamento_Hundegger"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">16</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">111L</v>
                                      </o>
                                      <v n="Id">110L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"I_Macinatore_Run"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">107L</v>
                                      </o>
                                      <v n="Id">106L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">109L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"M_Ciclo_Svuotamento_Hdd_RUN"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">true</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">101L</v>
                                  </o>
                                  <v n="Id">100L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <n n="EN" />
                              <n n="ENO" />
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">99L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"TS_AreaM_ON"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">32L</v>
                              </o>
                              <v n="Id">31L</v>
                            </o>
                            <o t="BoxTreeBox">
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">112L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" />
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeOperand">
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"TON_Macinatore_On.Q"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">1</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">true</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">103L</v>
                                  </o>
                                  <v n="Id">102L</v>
                                </o>
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"I_Macinatore_Run"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">true</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">115L</v>
                                  </o>
                                  <v n="Id">114L</v>
                                </o>
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"TS"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">1</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">true</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">214L</v>
                                  </o>
                                  <v n="Id">213L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <n n="EN" />
                              <n n="ENO" />
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">113L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"TON_Ciclo_Macinatore.Q"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">1</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">206L</v>
                              </o>
                              <v n="Id">205L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">28L</v>
                        </o>
                        <v n="Id">36L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">12L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"start macinatore"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems">
                      <o t="BoxTreeDemux">
                        <v n="VarId">7</v>
                        <o n="Input" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"M_Ciclo_Svuotamento_Hdd_RUN"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">57L</v>
                          </o>
                          <v n="Id">56L</v>
                        </o>
                        <v n="Id">55L</v>
                      </o>
                      <o t="BoxTreeAssign">
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_Auto_Start_Macinatore"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">201L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeDemux">
                          <v n="VarId">7</v>
                          <n n="Input" />
                          <v n="Id">58L</v>
                        </o>
                        <v n="Id">60L</v>
                      </o>
                      <o t="BoxTreeBox">
                        <v n="BoxType">"TON"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"TON_Macinatore_On"</v>
                          <v n="Type">"TON"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">61L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">63L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeDemux">
                            <v n="VarId">7</v>
                            <n n="Input" />
                            <v n="Id">64L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"T#30S"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">66L</v>
                            </o>
                            <v n="Id">65L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>IN</v>
                            <v>PT</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Q</v>
                            <v>ET</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">62L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">54L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"start manuale vibro Hundegger"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_Man_Start_Vibro_Hdd"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">255L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">249L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"TS_AreaM_ON"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">252L</v>
                              </o>
                              <v n="Id">251L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"I_Pls_Start_Vibro_Hdd"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">254L</v>
                              </o>
                              <v n="Id">253L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">250L</v>
                        </o>
                        <v n="Id">256L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">248L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"start vibro macinatore"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems">
                      <o t="BoxTreeDemux">
                        <v n="VarId">37</v>
                        <o n="Input" t="BoxTreeBox">
                          <v n="BoxType">"OR"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">257L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"TON_Macinatore_On.Q"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">70L</v>
                              </o>
                              <v n="Id">69L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"M_Man_Start_Vibro_Hdd"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">260L</v>
                              </o>
                              <v n="Id">259L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">Or</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">258L</v>
                        </o>
                        <v n="Id">68L</v>
                      </o>
                      <o t="BoxTreeDemux">
                        <v n="VarId">38</v>
                        <o n="Input" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">264L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeDemux">
                              <v n="VarId">37</v>
                              <n n="Input" />
                              <v n="Id">71L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"TON_Macinatore_On.Q"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">267L</v>
                              </o>
                              <v n="Id">266L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">265L</v>
                        </o>
                        <v n="Id">268L</v>
                      </o>
                      <o t="BoxTreeAssign">
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_Auto_Start_Vibro_Macinatore"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">202L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeDemux">
                          <v n="VarId">38</v>
                          <n n="Input" />
                          <v n="Id">269L</v>
                        </o>
                        <v n="Id">73L</v>
                      </o>
                      <o t="BoxTreeBox">
                        <v n="BoxType">"TON"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"TON_Vibro_Macinatore_On"</v>
                          <v n="Type">"TON"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">271L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">273L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeDemux">
                            <v n="VarId">38</v>
                            <n n="Input" />
                            <v n="Id">270L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"T#30S"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">275L</v>
                            </o>
                            <v n="Id">274L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>IN</v>
                            <v>PT</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Q</v>
                            <v>ET</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">272L</v>
                      </o>
                      <o t="BoxTreeAssign">
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"HQ1_T3_KA3"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">262L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeDemux">
                          <v n="VarId">37</v>
                          <n n="Input" />
                          <v n="Id">261L</v>
                        </o>
                        <v n="Id">263L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">67L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"start vibro hundegger"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems">
                      <o t="BoxTreeDemux">
                        <v n="VarId">39</v>
                        <o n="Input" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TON_Vibro_Macinatore_On.Q"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">38L</v>
                          </o>
                          <v n="Id">37L</v>
                        </o>
                        <v n="Id">46L</v>
                      </o>
                      <o t="BoxTreeAssign">
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"M_Auto_Start_Vibro_Hdd"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">203L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeDemux">
                          <v n="VarId">39</v>
                          <n n="Input" />
                          <v n="Id">47L</v>
                        </o>
                        <v n="Id">40L</v>
                      </o>
                      <o t="BoxTreeAssign">
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"HQ1_T2_KA2"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">239L</v>
                            </o>
                            <o>
                              <v n="Operand">"HQ1_T1_KA1"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">237L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeDemux">
                          <v n="VarId">39</v>
                          <n n="Input" />
                          <v n="Id">236L</v>
                        </o>
                        <v n="Id">238L</v>
                      </o>
                      <o t="BoxTreeBox">
                        <v n="BoxType">"TON"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"TON_Ciclo_Macinatore"</v>
                          <v n="Type">"TON"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">49L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">51L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeDemux">
                            <v n="VarId">39</v>
                            <n n="Input" />
                            <v n="Id">48L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"Tempo_Svuotamento_Hdd"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">53L</v>
                            </o>
                            <v n="Id">52L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>IN</v>
                            <v>PT</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Q</v>
                            <v>ET</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">50L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">11L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"inizializzazione tempo ciclo svuotamento"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MOVE"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">""</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">125L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"Tempo_Svuotamento_Hdd"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">127L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeBox">
                            <v n="BoxType">"EQ"</v>
                            <o n="Instance" t="Operand">
                              <n n="Operand" />
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">128L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems">
                                <n />
                              </l2>
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems">
                              <o t="BoxTreeBox">
                                <v n="BoxType">"OR"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">130L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" />
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems" cet="BoxTreeOperand">
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"TON_Vibro_Macinatore_On.Q"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">133L</v>
                                    </o>
                                    <v n="Id">132L</v>
                                  </o>
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"TON_Vibro_Macinatore_On.Q"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">1</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">135L</v>
                                    </o>
                                    <v n="Id">134L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <v n="CallType" t="Operator">Or</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">131L</v>
                              </o>
                              <o t="BoxTreeOperand">
                                <o n="Operand" t="Operand">
                                  <v n="Operand">"Tempo_Svuotamento_Hdd"</v>
                                  <v n="Type">"TIME"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">137L</v>
                                </o>
                                <v n="Id">136L</v>
                              </o>
                              <o t="BoxTreeOperand">
                                <o n="Operand" t="Operand">
                                  <v n="Operand">"t#0m"</v>
                                  <v n="Type">"TIME"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">139L</v>
                                </o>
                                <v n="Id">138L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v>EN</v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                              </l2>
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v></v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                              </l2>
                            </o>
                            <v n="CallType" t="Operator">Eq</v>
                            <v n="EN">true</v>
                            <v n="ENO">false</v>
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">129L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"t#5m"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">141L</v>
                            </o>
                            <v n="Id">140L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v></v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v></v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">Move</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">126L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">124L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"richiesta start macinatore"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"HQ1_M_ON"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">189L</v>
                            </o>
                            <o>
                              <v n="Operand">"M_Start_Req_Stop_Macinatore"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">159L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">167L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" />
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"TP"</v>
                              <o n="Instance" t="Operand">
                                <v n="Operand">"TP_Start_Macinatore"</v>
                                <v n="Type">"TP"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">163L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" cet="Operand">
                                  <n />
                                  <o>
                                    <v n="Operand">""</v>
                                    <v n="Type">"TIME"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">true</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">154L</v>
                                  </o>
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"OR"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">176L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"M_Ciclo_Svuotamento_Hdd_RUN"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">156L</v>
                                      </o>
                                      <v n="Id">155L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"M_PO1.btn_M_MacOn"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">179L</v>
                                      </o>
                                      <v n="Id">178L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">Or</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">177L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"t#5s"</v>
                                    <v n="Type">"TIME"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">158L</v>
                                  </o>
                                  <v n="Id">157L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>IN</v>
                                  <v>PT</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>TIME</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>Q</v>
                                  <v>ET</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>TIME</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">FunctionBlock</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">164L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"TS_AreaM_ON"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">172L</v>
                              </o>
                              <v n="Id">171L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">168L</v>
                        </o>
                        <v n="Id">160L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">151L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">"richiesta stop macinatore"</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"HQ1_M_OFF"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">190L</v>
                            </o>
                            <o>
                              <v n="Operand">"M_Stop_Req_Stop_Macinatore"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">149L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"TP"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"TP_Stop_Macinatore"</v>
                            <v n="Type">"TP"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">161L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">""</v>
                                <v n="Type">"TIME"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">146L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">185L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" />
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">207L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems" />
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"M_Ciclo_Svuotamento_Hdd_RUN"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">1</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">212L</v>
                                      </o>
                                      <v n="Id">211L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"M_PO1.btn_0_AreaMoff"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">16</v>
                                          <v n="Fixed">true</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">true</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">188L</v>
                                      </o>
                                      <v n="Id">187L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <n n="EN" />
                                  <n n="ENO" />
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">208L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"TS_AreaM_ON"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">32</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">true</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">200L</v>
                                  </o>
                                  <v n="Id">199L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <n n="EN" />
                              <n n="ENO" />
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">186L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"t#5s"</v>
                                <v n="Type">"TIME"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">148L</v>
                              </o>
                              <v n="Id">147L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>IN</v>
                              <v>PT</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Q</v>
                              <v>ET</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">162L</v>
                        </o>
                        <v n="Id">150L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">120L</v>
                  </o>
                </l2>
                <v n="BranchCounter">39</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeDemux">{b1d55618-017c-4bc5-990a-55c2f27d9d3a}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="act_OUTPUT" Id="{6e350841-508c-4dfd-aeea-77afb98e80fc}">
      <Implementation>
        <ST><![CDATA[
IF NOT bSIMULA_out THEN
	
	//TERM9 EL2008 H-Q1
	glo_dig_out_HQ1[1]		:=	Dis_Scarico_Hundegger;//S1_U1;									//DIGOUT CH1		Valvola aria pulizia ingresso M12
	glo_dig_out_HQ1[2]		:=	HQ1_T1_KA1;								//DIGOUT CH2		T1 Vibrotrasp buca
	glo_dig_out_HQ1[3]		:=	HQ1_T2_KA2;								//DIGOUT CH3		T2 Nastro elev buca
	glo_dig_out_HQ1[4]		:=	HQ1_T3_KA3;// AND NOT SensInMac;			//DIGOUT CH4		T3 Vibrotrasp macinatore
	glo_dig_out_HQ1[5]		:=	HQ1_T5M2_A_KA4;							//DIGOUT CH5		Apre scarico trasp orizz
	glo_dig_out_HQ1[6]		:=	HQ1_T5_KA5;								//DIGOUT CH6		Trasp elevat a parete
	glo_dig_out_HQ1[7]		:=	HQ1_T6_KA6;								//DIGOUT CH7		Trasp orizza a parete
	glo_dig_out_HQ1[8]		:=	HQ1_T5M2_C_KA7;							//DIGOUT CH8		Chiude scarico trasp orizz
	
	//TERM10 EL2008 H-Q1
	glo_dig_out_HQ1[9]		:= HQ1_T7_A_KA8;							//DIGOUT CH1		Caricatore macinat Avanti
	glo_dig_out_HQ1[10]		:= HQ1_T7_I_KA9;							//DIGOUT CH2		Caricatore macinat Indietro
	glo_dig_out_HQ1[11]		:= HQ1_M_ON;								//DIGOUT CH3		Macinatore ON impulsivo
	glo_dig_out_HQ1[12]		:= HQ1_M_OFF;								//DIGOUT CH4		Macinatore OFF impulsivo
	glo_dig_out_HQ1[13]		:= HQ1_T4_KA4;								//DIGOUT CH5		T4 Trasportatore silos macinatore	
	glo_dig_out_HQ1[14]		:= HQ1_S1_ValvolaStellare;					//DIGOUT CH6		Valvola stellare scarico silos 1	
	glo_dig_out_HQ1[15]		:= HQ1_RaclaON;								//DIGOUT CH7		Rancia: avviata da quadro silos
	glo_dig_out_HQ1[16]		:= HQ1_BrichettatriceON;					//DIGOUT CH8		Bricchettatrice: avviata da quadro silos

	//M_PO1											
	//IOLINK CH4		PULSANTIERA BNI005M
	glo_dig_out_T3C01[5] 	:= M_PO1.led_M_MacOn;						//BOTTONE '0'
	glo_dig_out_T3C01[8]	:= M_PO1.led_R_Riarmo;						//BOTTONE 'r'
	glo_dig_out_T3C01[6]	:= M_PO1.led_0_AreaMoff;					//TASTO 'M'
	
	//S1_PO1											
	//IOLINK CH4		PULSANTIERA BNI005M
					//BOTTONE 'r'

END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_Semafori" Id="{0db9c996-8963-4ea6-9007-70f6a4a157fb}">
      <Implementation>
        <ST><![CDATA[
//#######################################################
//####################    SEMAFORI   ####################
//#######################################################

IF TS_AreaM_ON THEN
	IF I_Macinatore_Run  THEN
		fbS1_Se1(bON:= TRUE, sColore:= 3, bBlink:= TRUE, semaforo=> S1_Se1);	//verde	
	ELSE
		fbS1_Se1(bON:= TRUE, sColore:= 4, bBlink:= TRUE, semaforo=> S1_Se1);	//arancio
	END_IF
ELSE	
	fbS1_Se1(bON:= TRUE, sColore:= 2, bBlink:= TRUE, semaforo=> S1_Se1);	//rosso
END_IF




]]></ST>
      </Implementation>
    </Action>
    <Action Name="act_Sensori" Id="{d689a64f-5d94-4c3a-aecf-b9256c3086c6}">
      <Implementation>
        <ST><![CDATA[
//#######################################################
//####################    SENSORI   #####################
//#######################################################
//SOTTO HUNDEGGER
//CODA CIRCOLARE VALORI SENSORE inbit
T1SO1tmravg(IN:=TRUE,PT:=T#200MS);
T1SO1maxCnt:= REAL_TO_INT(T1SO1maxTimeavg*1000/200);
IF T1SO1maxCnt > 99 THEN
	T1SO1maxCnt:=99;
END_IF
IF T1SO1tmravg.Q THEN
	T1SO1tmravg(IN:=FALSE);	
	//CONTATORE TEMPO MASSIMO CAMPIONATURA
	IF T1SO1cnt < T1SO1maxCnt-1 THEN
		T1SO1cnt:=T1SO1cnt+1;	
	ELSE
		T1SO1cnt:=0;
	END_IF
	//POPOLO ARRAY LETTURE SENSORE in bit			
	T1SO1arravg[T1SO1cnt]:= T1_SO1;
END_IF
//MEDIA VALORI inbit
T1SO1cnt3:=0;
T1SO1sumavg:=0;
FOR T1SO1cnt2:=1 TO T1SO1maxCnt-1 DO
	IF T1SO1arravg[T1SO1cnt2] > 0 THEN
		T1SO1sumavg:= T1SO1sumavg + T1SO1arravg[T1SO1cnt2];
		T1SO1cnt3:=T1SO1cnt3+1;
	END_IF
END_FOR
IF T1SO1sumavg > 0 THEN
	T1SO1avg:=(T1SO1sumavg/T1SO1cnt3);	
END_IF
T1.SO1_fb(
	lettura:= REAL_TO_INT(T1SO1avg), 
	distanzaAVuoto:=6150,
	valSoglia:= solgiaT1SO1, 
	filtertime:=0,
	full=> appT1S01_Full);		
	
	//T1S01 full ritardato di 10 secondi 
	tmrT1S01_Full(IN:=appT1S01_Full,PT:=T#10S);
	T1.SO1_full := tmrT1S01_Full.Q;
	
//INGRESSO al T3
//CODA CIRCOLARE VALORI SENSORE inbit
T3S1tmravg(IN:=TRUE,PT:=T#200MS);
T3S1maxCnt:= REAL_TO_INT(T3S1maxTimeavg*1000/200);
IF T3S1maxCnt > 99 THEN
	T3S1maxCnt:=99;
END_IF
IF T3S1tmravg.Q THEN
	T3S1tmravg(IN:=FALSE);	
	//CONTATORE TEMPO MASSIMO CAMPIONATURA
	IF T3S1cnt < T3S1maxCnt-1 THEN
		T3S1cnt:=T3S1cnt+1;	
	ELSE
		T3S1cnt:=0;
	END_IF
	//POPOLO ARRAY LETTURE SENSORE in bit			
	T3S1arravg[T3S1cnt]:= T3_S1;
END_IF
//MEDIA VALORI inbit
T3S1cnt3:=0;
T3S1sumavg:=0;
FOR T3S1cnt2:=1 TO T3S1maxCnt-1 DO
	IF T3S1arravg[T3S1cnt2] > 0 THEN
		T3S1sumavg:= T3S1sumavg + T3S1arravg[T3S1cnt2];
		T3S1cnt3:=T3S1cnt3+1;
	END_IF
END_FOR
IF T3S1sumavg > 0 THEN
	T3S1avg:=(T3S1sumavg/T3S1cnt3);	
END_IF
T3.S1_fb(
	lettura:= REAL_TO_INT(T3S1avg), 
	maxScaleBit:= 32767, 
	maxScaleIng:= 1300, 
	deltaLowLimit:= 30,
	distanzaAVuoto:=1173,
	valSoglia:= sogliaT3S1, 
	filterTime:=2,
	full=> T3.S1_full,
	actualVal=> T3.S1_actVal);


//USCITA al T3	
//CODA CIRCOLARE VALORI SENSORE inbit
T3S2tmravg(IN:=TRUE,PT:=T#200MS);
T3S2maxCnt:= REAL_TO_INT(T3S2maxTimeavg*1000/200);
IF T3S2maxCnt > 99 THEN
	T3S2maxCnt:=99;
END_IF
IF T3S2tmravg.Q THEN
	T3S2tmravg(IN:=FALSE);	
	//CONTATORE TEMPO MASSIMO CAMPIONATURA
	IF T3S2cnt < T3S2maxCnt-1 THEN
		T3S2cnt:=T3S2cnt+1;	
	ELSE
		T3S2cnt:=0;
	END_IF
	//POPOLO ARRAY LETTURE SENSORE in bit			
	T3S2arravg[T3S2cnt]:= T3_S2;
END_IF
//MEDIA VALORI inbit
T3S2cnt3:=0;
T3S2sumavg:=0;
FOR T3S2cnt2:=1 TO T3S2maxCnt-1 DO
	IF T3S2arravg[T3S2cnt2] > 0 THEN
		T3S2sumavg:= T3S2sumavg + T3S2arravg[T3S2cnt2];
		T3S2cnt3:=T3S2cnt3+1;
	END_IF
END_FOR
IF T3S2sumavg > 0 THEN
	T3S2avg:=(T3S2sumavg/T3S2cnt3);	
END_IF	
T3.S2_fb(
	lettura:= REAL_TO_INT(T3S2avg), 
	maxScaleBit:= 32767, 
	maxScaleIng:= 1300, 
	deltaLowLimit:= 30,
	distanzaAVuoto:=590,
	valSoglia:= sogliaT3S2, 
	filterTime:=2,
	full=> T3.S2_full,
	actualVal=> T3.S2_actVal);


	

//SILOS1	
//CODA CIRCOLARE VALORI SENSORE inbit
S1SO2tmravg(IN:=TRUE,PT:=T#200MS);
S1SO2maxCnt:= REAL_TO_INT(S1SO2maxTimeavg*1000/200);
IF S1SO2maxCnt > 99 THEN
	S1SO2maxCnt:=99;
END_IF
IF S1SO2tmravg.Q THEN
	S1SO2tmravg(IN:=FALSE);	
	//CONTATORE TEMPO MASSIMO CAMPIONATURA
	IF S1SO2cnt < S1SO2maxCnt-1 THEN
		S1SO2cnt:=S1SO2cnt+1;	
	ELSE
		S1SO2cnt:=0;
	END_IF
	//POPOLO ARRAY LETTURE SENSORE in bit			
	S1SO2arravg[S1SO2cnt]:= S1_SO2;
END_IF
//MEDIA VALORI inbit
S1SO2cnt3:=0;
S1SO2sumavg:=0;
FOR S1SO2cnt2:=1 TO S1SO2maxCnt-1 DO
	IF S1SO2arravg[S1SO2cnt2] > 0 THEN
		S1SO2sumavg:= S1SO2sumavg + S1SO2arravg[S1SO2cnt2];
		S1SO2cnt3:=S1SO2cnt3+1;
	END_IF
END_FOR
IF S1SO2sumavg > 0 THEN
	S1SO2avg:=(S1SO2sumavg/S1SO2cnt3);	
END_IF
(*
S1.SO2_fb(
	lettura:= REAL_TO_INT(S1SO2avg), 
	maxScaleBit:= 32767, 
	maxScaleIng:= 6000, 
	deltaLowLimit:= 30, 
	distanzaAVuoto:=3250,
	valSoglia:= sogliaS1SO2, 
	filterTime:=1,
	full=> SO2_full_curr, //S1.SO2_full,
	actualVal=>S1.SO2_actVal);
	
	
	tmrValidaSoglia_S02(IN:= SO2_full_curr, PT:=T#15S);
	IF tmrValidaSoglia_S02.Q THEN
		tmrValidaSoglia_S02(IN:= FALSE);
		S1.SO2_full:= TRUE;
	END_IF
	
	IF NOT SO2_full_curr THEN
		S1.SO2_full:= FALSE;
	END_IF
	*)
	
//sensore livello silos (sensore in basso)

tmrS1_T_Rit_Empty(IN:=S1_S1,PT:=T#15m);
	S1.SO2_full:= TRUE;//tmrS1_T_Rit_Empty.Q OR Forza_TT1S01_Full;
	
//x HMI
glo_ES_ActVal.S1_S02:=S1.SO2_actVal;
altMatS1SO2:= S1.SO2_fb.distanzaAVuoto - glo_ES_ActVal.S1_S02;		
IF altMatS1SO2 <0 THEN
	altMatS1SO2:=0;
END_IF			
	


//SILOS2
S2.S1_fb(
	lettura:= S2_S1, 
	maxScaleBit:= 32767, 
	maxScaleIng:= 6000, 
	deltaLowLimit:= 30, 
	distanzaAVuoto:=6000,
	valSoglia:= 2000, 
	full=> S2.S1_full,
	actualVal=>S2.S1_actVal);
		
		
		
		
		
		
		
		
	]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="EVACUAZIONE_SCARTI">
      <LineId Id="292" Count="9" />
      <LineId Id="435" Count="0" />
      <LineId Id="434" Count="0" />
      <LineId Id="302" Count="2" />
      <LineId Id="307" Count="0" />
      <LineId Id="305" Count="1" />
      <LineId Id="5" Count="0" />
      <LineId Id="312" Count="0" />
      <LineId Id="311" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_ALARM">
      <LineId Id="133" Count="0" />
      <LineId Id="152" Count="0" />
      <LineId Id="165" Count="1" />
      <LineId Id="164" Count="0" />
      <LineId Id="161" Count="0" />
      <LineId Id="153" Count="0" />
      <LineId Id="159" Count="1" />
      <LineId Id="154" Count="4" />
      <LineId Id="135" Count="0" />
      <LineId Id="138" Count="1" />
      <LineId Id="141" Count="3" />
      <LineId Id="140" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="108" Count="17" />
      <LineId Id="162" Count="0" />
      <LineId Id="126" Count="1" />
      <LineId Id="145" Count="0" />
      <LineId Id="132" Count="0" />
      <LineId Id="149" Count="0" />
      <LineId Id="131" Count="0" />
      <LineId Id="1" Count="0" />
      <LineId Id="61" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="44" Count="1" />
      <LineId Id="47" Count="2" />
      <LineId Id="46" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="50" Count="0" />
      <LineId Id="54" Count="1" />
      <LineId Id="59" Count="1" />
      <LineId Id="56" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="163" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="107" Count="0" />
      <LineId Id="146" Count="0" />
      <LineId Id="102" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="3" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="15" Count="1" />
      <LineId Id="24" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="147" Count="1" />
      <LineId Id="6" Count="0" />
      <LineId Id="71" Count="0" />
      <LineId Id="64" Count="2" />
      <LineId Id="68" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="73" Count="1" />
      <LineId Id="72" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="150" Count="1" />
      <LineId Id="9" Count="0" />
      <LineId Id="18" Count="1" />
      <LineId Id="17" Count="0" />
      <LineId Id="42" Count="1" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_AreaMac_AUTO">
      <LineId Id="1645" Count="9" />
      <LineId Id="1981" Count="0" />
      <LineId Id="1656" Count="2" />
      <LineId Id="1716" Count="0" />
      <LineId Id="1659" Count="0" />
      <LineId Id="1664" Count="0" />
      <LineId Id="1466" Count="0" />
      <LineId Id="1974" Count="0" />
      <LineId Id="1670" Count="2" />
      <LineId Id="1679" Count="0" />
      <LineId Id="1676" Count="0" />
      <LineId Id="1678" Count="0" />
      <LineId Id="1680" Count="1" />
      <LineId Id="1673" Count="0" />
      <LineId Id="1683" Count="1" />
      <LineId Id="1686" Count="0" />
      <LineId Id="1898" Count="0" />
      <LineId Id="1863" Count="0" />
      <LineId Id="1685" Count="0" />
      <LineId Id="1682" Count="0" />
      <LineId Id="1468" Count="0" />
      <LineId Id="1674" Count="1" />
      <LineId Id="1485" Count="9" />
      <LineId Id="1501" Count="0" />
      <LineId Id="1751" Count="1" />
      <LineId Id="1503" Count="0" />
      <LineId Id="1512" Count="1" />
      <LineId Id="1935" Count="0" />
      <LineId Id="1514" Count="0" />
      <LineId Id="1520" Count="1" />
      <LineId Id="1515" Count="1" />
      <LineId Id="1522" Count="0" />
      <LineId Id="1959" Count="0" />
      <LineId Id="1817" Count="0" />
      <LineId Id="1930" Count="0" />
      <LineId Id="1837" Count="0" />
      <LineId Id="1523" Count="0" />
      <LineId Id="1774" Count="1" />
      <LineId Id="1524" Count="0" />
      <LineId Id="1517" Count="1" />
      <LineId Id="1834" Count="0" />
      <LineId Id="1525" Count="0" />
      <LineId Id="1819" Count="0" />
      <LineId Id="1910" Count="0" />
      <LineId Id="1820" Count="1" />
      <LineId Id="1527" Count="1" />
      <LineId Id="1936" Count="0" />
      <LineId Id="1918" Count="0" />
      <LineId Id="1957" Count="0" />
      <LineId Id="1926" Count="0" />
      <LineId Id="1925" Count="0" />
      <LineId Id="1921" Count="0" />
      <LineId Id="1964" Count="0" />
      <LineId Id="1966" Count="0" />
      <LineId Id="1969" Count="1" />
      <LineId Id="1967" Count="1" />
      <LineId Id="1826" Count="0" />
      <LineId Id="1947" Count="0" />
      <LineId Id="1956" Count="0" />
      <LineId Id="1951" Count="1" />
      <LineId Id="1954" Count="1" />
      <LineId Id="1948" Count="0" />
      <LineId Id="1946" Count="0" />
      <LineId Id="1827" Count="0" />
      <LineId Id="1835" Count="0" />
      <LineId Id="1828" Count="0" />
      <LineId Id="1830" Count="2" />
      <LineId Id="1530" Count="0" />
      <LineId Id="1519" Count="0" />
      <LineId Id="1829" Count="0" />
      <LineId Id="1822" Count="0" />
      <LineId Id="1509" Count="0" />
      <LineId Id="1933" Count="0" />
      <LineId Id="1511" Count="0" />
      <LineId Id="1534" Count="0" />
      <LineId Id="1510" Count="0" />
      <LineId Id="1504" Count="0" />
      <LineId Id="1668" Count="0" />
      <LineId Id="1753" Count="0" />
      <LineId Id="1838" Count="0" />
      <LineId Id="1938" Count="0" />
      <LineId Id="1841" Count="2" />
      <LineId Id="1934" Count="0" />
      <LineId Id="1839" Count="1" />
      <LineId Id="1472" Count="1" />
      <LineId Id="1850" Count="0" />
      <LineId Id="1535" Count="10" />
      <LineId Id="1474" Count="0" />
      <LineId Id="1759" Count="0" />
      <LineId Id="2090" Count="0" />
      <LineId Id="2092" Count="0" />
      <LineId Id="2094" Count="0" />
      <LineId Id="2091" Count="0" />
      <LineId Id="1547" Count="0" />
      <LineId Id="2095" Count="0" />
      <LineId Id="1760" Count="0" />
      <LineId Id="2084" Count="0" />
      <LineId Id="2088" Count="1" />
      <LineId Id="2087" Count="0" />
      <LineId Id="1546" Count="0" />
      <LineId Id="1548" Count="0" />
      <LineId Id="1551" Count="0" />
      <LineId Id="1943" Count="0" />
      <LineId Id="1706" Count="0" />
      <LineId Id="1810" Count="0" />
      <LineId Id="1802" Count="0" />
      <LineId Id="1609" Count="0" />
      <LineId Id="1804" Count="0" />
      <LineId Id="1779" Count="0" />
      <LineId Id="1901" Count="0" />
      <LineId Id="1945" Count="0" />
      <LineId Id="1906" Count="0" />
      <LineId Id="1902" Count="0" />
      <LineId Id="1904" Count="0" />
      <LineId Id="1944" Count="0" />
      <LineId Id="1909" Count="0" />
      <LineId Id="1905" Count="0" />
      <LineId Id="1903" Count="0" />
      <LineId Id="1620" Count="0" />
      <LineId Id="1553" Count="0" />
      <LineId Id="1707" Count="0" />
      <LineId Id="1559" Count="0" />
      <LineId Id="1899" Count="0" />
      <LineId Id="2096" Count="0" />
      <LineId Id="1567" Count="0" />
      <LineId Id="1786" Count="1" />
      <LineId Id="1791" Count="0" />
      <LineId Id="1900" Count="0" />
      <LineId Id="1792" Count="0" />
      <LineId Id="1782" Count="0" />
      <LineId Id="1568" Count="1" />
      <LineId Id="1813" Count="0" />
      <LineId Id="1570" Count="1" />
      <LineId Id="1642" Count="0" />
      <LineId Id="2030" Count="0" />
      <LineId Id="1982" Count="0" />
      <LineId Id="2012" Count="0" />
      <LineId Id="2027" Count="0" />
      <LineId Id="1572" Count="1" />
      <LineId Id="1625" Count="0" />
      <LineId Id="1561" Count="0" />
      <LineId Id="1815" Count="0" />
      <LineId Id="1628" Count="2" />
      <LineId Id="1907" Count="0" />
      <LineId Id="1632" Count="0" />
      <LineId Id="2028" Count="0" />
      <LineId Id="1983" Count="0" />
      <LineId Id="2011" Count="0" />
      <LineId Id="2026" Count="0" />
      <LineId Id="1639" Count="0" />
      <LineId Id="1908" Count="0" />
      <LineId Id="1631" Count="0" />
      <LineId Id="1633" Count="1" />
      <LineId Id="1814" Count="0" />
      <LineId Id="1635" Count="2" />
      <LineId Id="1640" Count="0" />
      <LineId Id="1627" Count="0" />
      <LineId Id="1626" Count="0" />
      <LineId Id="1554" Count="0" />
      <LineId Id="1809" Count="0" />
      <LineId Id="1801" Count="0" />
      <LineId Id="1556" Count="0" />
      <LineId Id="1555" Count="0" />
      <LineId Id="1550" Count="0" />
      <LineId Id="1549" Count="0" />
      <LineId Id="1480" Count="0" />
      <LineId Id="1762" Count="0" />
      <LineId Id="1844" Count="0" />
      <LineId Id="754" Count="0" />
      <LineId Id="1939" Count="0" />
      <LineId Id="1847" Count="2" />
      <LineId Id="1845" Count="1" />
      <LineId Id="772" Count="0" />
      <LineId Id="1851" Count="1" />
      <LineId Id="775" Count="3" />
      <LineId Id="1197" Count="1" />
      <LineId Id="1200" Count="2" />
      <LineId Id="1199" Count="0" />
      <LineId Id="1688" Count="0" />
      <LineId Id="1766" Count="2" />
      <LineId Id="1690" Count="0" />
      <LineId Id="1692" Count="0" />
      <LineId Id="1941" Count="0" />
      <LineId Id="1696" Count="0" />
      <LineId Id="1704" Count="0" />
      <LineId Id="1714" Count="0" />
      <LineId Id="1705" Count="0" />
      <LineId Id="1697" Count="0" />
      <LineId Id="1709" Count="0" />
      <LineId Id="1942" Count="0" />
      <LineId Id="1888" Count="1" />
      <LineId Id="1897" Count="0" />
      <LineId Id="1893" Count="1" />
      <LineId Id="1891" Count="1" />
      <LineId Id="1890" Count="0" />
      <LineId Id="1698" Count="0" />
      <LineId Id="1895" Count="0" />
      <LineId Id="1699" Count="0" />
      <LineId Id="1693" Count="0" />
      <LineId Id="1715" Count="0" />
      <LineId Id="1691" Count="0" />
      <LineId Id="1773" Count="0" />
      <LineId Id="1770" Count="0" />
      <LineId Id="1772" Count="0" />
      <LineId Id="1853" Count="0" />
      <LineId Id="1940" Count="0" />
      <LineId Id="1859" Count="1" />
      <LineId Id="1854" Count="1" />
      <LineId Id="1858" Count="0" />
      <LineId Id="556" Count="0" />
      <LineId Id="1870" Count="1" />
      <LineId Id="1989" Count="1" />
      <LineId Id="1884" Count="0" />
      <LineId Id="1880" Count="0" />
      <LineId Id="2007" Count="0" />
      <LineId Id="2010" Count="0" />
      <LineId Id="2009" Count="0" />
      <LineId Id="2013" Count="3" />
      <LineId Id="2025" Count="0" />
      <LineId Id="1997" Count="0" />
      <LineId Id="2003" Count="0" />
      <LineId Id="2019" Count="2" />
      <LineId Id="2024" Count="0" />
      <LineId Id="1999" Count="1" />
      <LineId Id="2037" Count="1" />
      <LineId Id="2001" Count="0" />
      <LineId Id="2050" Count="0" />
      <LineId Id="1996" Count="0" />
      <LineId Id="2046" Count="0" />
      <LineId Id="1881" Count="1" />
      <LineId Id="1872" Count="0" />
      <LineId Id="1927" Count="1" />
      <LineId Id="1883" Count="0" />
      <LineId Id="1985" Count="1" />
      <LineId Id="2071" Count="0" />
      <LineId Id="1929" Count="0" />
      <LineId Id="1875" Count="1" />
      <LineId Id="1213" Count="0" />
      <LineId Id="1877" Count="0" />
      <LineId Id="2069" Count="1" />
      <LineId Id="1879" Count="0" />
      <LineId Id="1378" Count="0" />
      <LineId Id="1744" Count="1" />
      <LineId Id="1379" Count="0" />
      <LineId Id="1746" Count="0" />
      <LineId Id="1717" Count="4" />
      <LineId Id="1971" Count="0" />
      <LineId Id="1722" Count="4" />
      <LineId Id="1281" Count="0" />
      <LineId Id="1728" Count="4" />
      <LineId Id="1972" Count="0" />
      <LineId Id="1733" Count="4" />
      <LineId Id="1727" Count="0" />
      <LineId Id="1739" Count="1" />
      <LineId Id="1742" Count="1" />
      <LineId Id="1738" Count="0" />
      <LineId Id="1376" Count="1" />
      <LineId Id="1287" Count="0" />
      <LineId Id="1299" Count="0" />
      <LineId Id="1216" Count="0" />
      <LineId Id="1309" Count="0" />
      <LineId Id="1221" Count="5" />
      <LineId Id="1228" Count="1" />
      <LineId Id="1348" Count="0" />
      <LineId Id="1233" Count="2" />
      <LineId Id="1237" Count="0" />
      <LineId Id="1862" Count="0" />
      <LineId Id="1238" Count="1" />
      <LineId Id="2083" Count="0" />
      <LineId Id="1240" Count="0" />
      <LineId Id="1243" Count="0" />
      <LineId Id="2053" Count="0" />
      <LineId Id="2061" Count="1" />
      <LineId Id="2064" Count="0" />
      <LineId Id="2058" Count="0" />
      <LineId Id="1335" Count="3" />
      <LineId Id="1347" Count="0" />
      <LineId Id="2082" Count="0" />
      <LineId Id="1322" Count="0" />
      <LineId Id="1340" Count="0" />
      <LineId Id="1252" Count="4" />
      <LineId Id="1886" Count="0" />
      <LineId Id="1257" Count="0" />
      <LineId Id="1887" Count="0" />
      <LineId Id="1258" Count="3" />
      <LineId Id="2066" Count="2" />
      <LineId Id="2065" Count="0" />
      <LineId Id="1428" Count="0" />
      <LineId Id="1443" Count="0" />
      <LineId Id="1429" Count="1" />
      <LineId Id="1444" Count="0" />
      <LineId Id="1431" Count="1" />
      <LineId Id="1447" Count="0" />
      <LineId Id="1268" Count="0" />
      <LineId Id="1442" Count="0" />
      <LineId Id="1269" Count="11" />
      <LineId Id="1211" Count="0" />
      <LineId Id="1393" Count="0" />
      <LineId Id="1381" Count="0" />
      <LineId Id="1380" Count="0" />
      <LineId Id="1392" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_AreaMac_MAN">
      <LineId Id="2" Count="0" />
      <LineId Id="49" Count="1" />
      <LineId Id="3" Count="0" />
      <LineId Id="69" Count="0" />
      <LineId Id="51" Count="0" />
      <LineId Id="4" Count="0" />
      <LineId Id="11" Count="8" />
      <LineId Id="54" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="55" Count="0" />
      <LineId Id="22" Count="22" />
      <LineId Id="56" Count="0" />
      <LineId Id="45" Count="1" />
      <LineId Id="57" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="59" Count="1" />
      <LineId Id="58" Count="0" />
      <LineId Id="61" Count="1" />
      <LineId Id="65" Count="0" />
      <LineId Id="67" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="63" Count="1" />
      <LineId Id="52" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_AreaSilos">
      <LineId Id="28" Count="7" />
      <LineId Id="126" Count="0" />
      <LineId Id="37" Count="4" />
      <LineId Id="127" Count="0" />
      <LineId Id="42" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="129" Count="3" />
      <LineId Id="45" Count="0" />
      <LineId Id="134" Count="0" />
      <LineId Id="128" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="142" Count="2" />
      <LineId Id="3" Count="2" />
      <LineId Id="140" Count="0" />
      <LineId Id="122" Count="3" />
      <LineId Id="97" Count="4" />
      <LineId Id="138" Count="1" />
      <LineId Id="102" Count="14" />
      <LineId Id="137" Count="0" />
      <LineId Id="136" Count="0" />
      <LineId Id="135" Count="0" />
      <LineId Id="118" Count="2" />
      <LineId Id="67" Count="0" />
      <LineId Id="121" Count="0" />
      <LineId Id="68" Count="0" />
      <LineId Id="54" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="57" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_HMI">
      <LineId Id="2" Count="3" />
      <LineId Id="1" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="8" Count="3" />
      <LineId Id="6" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="13" Count="1" />
      <LineId Id="18" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="21" Count="2" />
      <LineId Id="19" Count="0" />
      <LineId Id="25" Count="1" />
      <LineId Id="24" Count="0" />
      <LineId Id="39" Count="2" />
      <LineId Id="28" Count="0" />
      <LineId Id="42" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="29" Count="3" />
      <LineId Id="20" Count="0" />
      <LineId Id="36" Count="1" />
      <LineId Id="34" Count="0" />
      <LineId Id="44" Count="1" />
      <LineId Id="43" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="33" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_INIT">
      <LineId Id="2" Count="0" />
      <LineId Id="1" Count="0" />
      <LineId Id="3" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_INPUT">
      <LineId Id="2" Count="8" />
      <LineId Id="1" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="100" Count="0" />
      <LineId Id="98" Count="1" />
      <LineId Id="102" Count="0" />
      <LineId Id="69" Count="0" />
      <LineId Id="93" Count="1" />
      <LineId Id="103" Count="1" />
      <LineId Id="95" Count="0" />
      <LineId Id="22" Count="5" />
      <LineId Id="40" Count="3" />
      <LineId Id="28" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="29" Count="1" />
      <LineId Id="45" Count="3" />
      <LineId Id="31" Count="0" />
      <LineId Id="49" Count="0" />
      <LineId Id="32" Count="1" />
      <LineId Id="89" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="90" Count="0" />
      <LineId Id="92" Count="0" />
      <LineId Id="91" Count="0" />
      <LineId Id="105" Count="0" />
      <LineId Id="88" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="81" Count="6" />
      <LineId Id="80" Count="0" />
      <LineId Id="79" Count="0" />
      <LineId Id="38" Count="1" />
      <LineId Id="71" Count="0" />
      <LineId Id="75" Count="0" />
      <LineId Id="96" Count="0" />
      <LineId Id="77" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="61" Count="0" />
      <LineId Id="53" Count="5" />
      <LineId Id="51" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_OUTPUT">
      <LineId Id="15" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="73" Count="0" />
      <LineId Id="2" Count="4" />
      <LineId Id="74" Count="0" />
      <LineId Id="8" Count="1" />
      <LineId Id="1" Count="0" />
      <LineId Id="12" Count="2" />
      <LineId Id="11" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="19" Count="4" />
      <LineId Id="75" Count="0" />
      <LineId Id="80" Count="0" />
      <LineId Id="84" Count="0" />
      <LineId Id="81" Count="0" />
      <LineId Id="83" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="86" Count="1" />
      <LineId Id="89" Count="0" />
      <LineId Id="85" Count="0" />
      <LineId Id="67" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_Semafori">
      <LineId Id="2" Count="3" />
      <LineId Id="8" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="16" Count="1" />
      <LineId Id="19" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="7" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="EVACUAZIONE_SCARTI.act_Sensori">
      <LineId Id="546" Count="4" />
      <LineId Id="715" Count="27" />
      <LineId Id="714" Count="0" />
      <LineId Id="551" Count="5" />
      <LineId Id="743" Count="0" />
      <LineId Id="764" Count="1" />
      <LineId Id="763" Count="0" />
      <LineId Id="558" Count="1" />
      <LineId Id="657" Count="27" />
      <LineId Id="656" Count="0" />
      <LineId Id="560" Count="12" />
      <LineId Id="686" Count="27" />
      <LineId Id="685" Count="0" />
      <LineId Id="573" Count="40" />
      <LineId Id="653" Count="2" />
      <LineId Id="756" Count="0" />
      <LineId Id="615" Count="9" />
      <LineId Id="744" Count="4" />
      <LineId Id="750" Count="0" />
      <LineId Id="749" Count="0" />
      <LineId Id="751" Count="4" />
      <LineId Id="757" Count="0" />
      <LineId Id="760" Count="0" />
      <LineId Id="762" Count="0" />
      <LineId Id="761" Count="0" />
      <LineId Id="758" Count="1" />
      <LineId Id="625" Count="26" />
      <LineId Id="53" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>